### ISSUE TITLE
Linux Astron Compile

### ISSUE THREAD

**Issue by allenhagen** [gabrielfraser223/gabrielsserverstatussource#1]
Compile instructions for Astron using Ubuntu 14.04
Here are the steps I took to compile it. It took me several days to work out all the kinks so I am passing it along to you.

# Install necessary packages:
apt-get update
apt-get -y install build-essential git wget

# We also need FPM for package building, but it's not in the Apt repository. It
# should be installed via Gem. This is to deploy multi-servers so you don't really have to worry about that.
apt-get -y install ruby ruby-dev
gem install fpm

# Grab Astron build dependencies:
apt-get -y install cmake libssl-dev

# Manual boost build
wget http://downloads.sourceforge.net/project/boost/boost/1.57.0/boost_1_57_0.tar.gz
tar -zxf boost_1_57_0.tar.gz
cd boost_1_57_0 
./bootstrap.sh
./b2 install

# Install mongodb-dev
apt-get -y install scons
wget https://github.com/mongodb/mongo-cxx-driver/archive/legacy-1.0.0.tar.gz
tar -zxf legacy-1.0.0.tar.gz
cd mongo-cxx-driver-legacy-1.0.0
scons install
cd build/install
# This could be linked instead
cp -R ./* /usr/local/

# Yaml-Cpp:
wget https://yaml-cpp.googlecode.com/files/yaml-cpp-0.5.1.tar.gz
tar xzvf yaml-cpp-0.5.1.tar.gz
cd yaml-cpp-0.5.1 && cmake . && make
make install
ldconfig

# Clone the Astron repository
git clone git://github.com/astron/astron.git

cd astron

git checkout temp/mongodb-dbqueue

mkdir build
cd build
cmake ..
make

**Comment by gabrielfraser223** [comment]
Haha thank you for this.
